CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE TABLE IF NOT EXISTS "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE TABLE IF NOT EXISTS "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "users_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" bigint NOT NULL REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "users_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" bigint NOT NULL REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "users_user_groups_user_id_group_id_b88eab82_uniq" ON "users_user_groups" ("user_id", "group_id");
CREATE INDEX "users_user_groups_user_id_5f6f5a90" ON "users_user_groups" ("user_id");
CREATE INDEX "users_user_groups_group_id_9afc8d0e" ON "users_user_groups" ("group_id");
CREATE UNIQUE INDEX "users_user_user_permissions_user_id_permission_id_43338c45_uniq" ON "users_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "users_user_user_permissions_user_id_20aca447" ON "users_user_user_permissions" ("user_id");
CREATE INDEX "users_user_user_permissions_permission_id_0b93982e" ON "users_user_user_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE TABLE IF NOT EXISTS "addresses_barangay" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "addresses_street" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL, "barangay_id" bigint NOT NULL REFERENCES "addresses_barangay" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "addresses_street_name_barangay_id_7344c5ea_uniq" ON "addresses_street" ("name", "barangay_id");
CREATE INDEX "addresses_street_barangay_id_1318dafe" ON "addresses_street" ("barangay_id");
CREATE TABLE IF NOT EXISTS "lupon_members_schedule" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "day" varchar(10) NOT NULL, "lupon_member_id" bigint NOT NULL REFERENCES "lupon_members_luponmember" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "lupon_members_schedule_lupon_member_id_e497c59e" ON "lupon_members_schedule" ("lupon_member_id");
CREATE TABLE IF NOT EXISTS "cases_settlementtype" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "settlement_name" varchar(100) NOT NULL, "description" text NULL);
CREATE TABLE IF NOT EXISTS "cases_casetype" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "case_name" varchar(100) NOT NULL, "description" text NULL, "severity" integer NOT NULL);
CREATE TABLE IF NOT EXISTS "lupon_members_luponmember" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "first_name" varchar(50) NOT NULL, "last_name" varchar(50) NOT NULL, "middle_name" varchar(50) NULL, "birth_date" date NOT NULL, "sex" varchar(10) NOT NULL, "contact_number" varchar(20) NOT NULL, "barangay" varchar(100) NOT NULL, "street" varchar(100) NOT NULL, "additional_info" text NULL, "sched" text NULL CHECK ((JSON_VALID("sched") OR "sched" IS NULL)), "role" varchar(20) NOT NULL);
CREATE TABLE IF NOT EXISTS "documents_documenttemplate" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(200) NOT NULL, "template_type" varchar(50) NOT NULL, "html_content" text NOT NULL, "css_styles" text NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
CREATE TABLE IF NOT EXISTS "documents_generateddocument" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "case_number" varchar(100) NOT NULL, "generated_data" text NOT NULL CHECK ((JSON_VALID("generated_data") OR "generated_data" IS NULL)), "generated_html" text NOT NULL, "created_at" datetime NOT NULL, "template_id" bigint NOT NULL REFERENCES "documents_documenttemplate" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "documents_generateddocument_template_id_2929174a" ON "documents_generateddocument" ("template_id");
CREATE TABLE IF NOT EXISTS "hearings_hearing" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "hearing_date" date NULL, "time" time NULL, "remarks" text NULL, "hearing_status" varchar(20) NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "case_id" varchar(36) NOT NULL REFERENCES "cases_case" ("id") DEFERRABLE INITIALLY DEFERRED, "lupon_member_id" bigint NULL REFERENCES "lupon_members_luponmember" ("id") DEFERRABLE INITIALLY DEFERRED, "hearing_number" integer NULL);
CREATE INDEX "hearings_hearing_case_id_e8afb079" ON "hearings_hearing" ("case_id");
CREATE INDEX "hearings_hearing_lupon_member_id_c351827e" ON "hearings_hearing" ("lupon_member_id");
CREATE TABLE IF NOT EXISTS "case_documents_document" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(100) NOT NULL, "file" varchar(100) NOT NULL, "uploaded_at" datetime NOT NULL, "case_id" varchar(36) NOT NULL REFERENCES "cases_case" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "case_documents_document_case_id_b981bd70" ON "case_documents_document" ("case_id");
CREATE TABLE IF NOT EXISTS "users_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NULL, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL UNIQUE, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "birth_date" date NULL, "contact_number" varchar(20) NULL, "middle_name" varchar(50) NULL, "additional_info" text NULL, "barangay" varchar(100) NOT NULL, "sex" varchar(10) NULL, "street" varchar(100) NULL, "is_admin" bool NOT NULL, "is_superadmin" bool NOT NULL, "is_user" bool NOT NULL);
CREATE TABLE IF NOT EXISTS "respondents_respondent" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "first_name" varchar(50) NOT NULL, "last_name" varchar(50) NOT NULL, "middle_name" varchar(50) NULL, "birth_date" date NULL, "contact_number" varchar(20) NULL, "barangay" varchar(100) NOT NULL, "street" varchar(100) NULL, "additional_info" text NULL, "sex" varchar(10) NULL);
CREATE TABLE IF NOT EXISTS "complainants_complainant" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "first_name" varchar(50) NOT NULL, "last_name" varchar(50) NOT NULL, "middle_name" varchar(50) NULL, "birth_date" date NULL, "sex" varchar(10) NULL, "contact_number" varchar(20) NULL, "barangay" varchar(100) NOT NULL, "street" varchar(100) NULL, "additional_info" text NULL, "account_id" bigint NULL REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED, "with_account" bool NOT NULL);
CREATE INDEX "complainants_complainant_account_id_4586f0e6" ON "complainants_complainant" ("account_id");
CREATE TABLE IF NOT EXISTS "cases_case" ("id" varchar(36) NOT NULL PRIMARY KEY, "date_filed" datetime NOT NULL, "case_type_id" bigint NULL REFERENCES "cases_casetype" ("id") DEFERRABLE INITIALLY DEFERRED, "settlement_type_id" bigint NULL REFERENCES "cases_settlementtype" ("id") DEFERRABLE INITIALLY DEFERRED, "case_status" varchar(20) NOT NULL, "is_active" bool NOT NULL, "description" text NULL, "predicted_hearings" integer NULL, "remarks" text NULL, "rejection_section" varchar(30) NULL, "relationship_id" bigint NULL REFERENCES "cases_relationship" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "cases_case_case_type_id_30752f13" ON "cases_case" ("case_type_id");
CREATE INDEX "cases_case_settlement_type_id_589f9cdb" ON "cases_case" ("settlement_type_id");
CREATE TABLE IF NOT EXISTS "cases_case_complainants" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "case_id" varchar(36) NOT NULL REFERENCES "cases_case" ("id") DEFERRABLE INITIALLY DEFERRED, "complainant_id" bigint NOT NULL REFERENCES "complainants_complainant" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "cases_case_respondents" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "case_id" varchar(36) NOT NULL REFERENCES "cases_case" ("id") DEFERRABLE INITIALLY DEFERRED, "respondent_id" bigint NOT NULL REFERENCES "respondents_respondent" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "cases_case_complainants_case_id_complainant_id_83752de7_uniq" ON "cases_case_complainants" ("case_id", "complainant_id");
CREATE INDEX "cases_case_complainants_case_id_255fe8df" ON "cases_case_complainants" ("case_id");
CREATE INDEX "cases_case_complainants_complainant_id_7a025e96" ON "cases_case_complainants" ("complainant_id");
CREATE UNIQUE INDEX "cases_case_respondents_case_id_respondent_id_f5a0abe5_uniq" ON "cases_case_respondents" ("case_id", "respondent_id");
CREATE INDEX "cases_case_respondents_case_id_70af5f78" ON "cases_case_respondents" ("case_id");
CREATE INDEX "cases_case_respondents_respondent_id_db00fca2" ON "cases_case_respondents" ("respondent_id");
CREATE TABLE IF NOT EXISTS "cases_relationship" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "relationship" varchar(100) NOT NULL);
CREATE INDEX "cases_case_relationship_id_0e0369bc" ON "cases_case" ("relationship_id");
