# Generated by Django 5.2.7 on 2025-10-10 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='addresses.barangay')),
            ],
            options={
                'ordering': ['barangay__name', 'name'],
                'unique_together': {('name', 'barangay')},
            },
        ),
    ]
