# Generated by Django 5.2.7 on 2025-10-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondent',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
