# Generated by Django 5.2.7 on 2025-11-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0002_alter_respondent_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondent',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
