# Generated by Django 5.2.9 on 2026-01-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of Company, NGO, etc.', max_length=200)),
                ('representative_name', models.CharField(blank=True, help_text='Who is representing this org?', max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('barangay', models.CharField(default='Tetuan', max_length=100)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
