# Generated by Django 5.2.7 on 2025-12-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complainants', '0003_alter_complainant_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='complainant',
            name='with_account',
            field=models.BooleanField(default=False),
        ),
    ]
