# Generated by Django 5.2.9 on 2026-01-18 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0003_case_complainants_case_respondents'),
        ('lupon_members', '0003_luponmember_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('hearing_status', models.CharField(choices=[('filed', 'Filed'), ('pending_schedule', 'Pending Schedule'), ('scheduled', 'Scheduled'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('pending_decision', 'Pending Decision')], default='pending_schedule', max_length=20)),
                ('hearing_number', models.IntegerField(blank=True, null=True)),
                ('google_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='cases.case')),
                ('lupon_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hearings', to='lupon_members.luponmember')),
            ],
        ),
    ]
