# Generated by Django 5.2.7 on 2025-10-10 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_remove_case_description_case_case_status_and_more'),
        ('lupon_members', '0002_alter_luponmember_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_date', models.DateField()),
                ('time', models.TimeField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('hearing_status', models.CharField(choices=[('pending_schedule', 'Pending Schedule'), ('scheduled', 'Scheduled'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('pending_decision', 'Pending Decision')], default='pending_schedule', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='cases.case')),
                ('lupon_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hearings', to='lupon_members.luponmember')),
            ],
        ),
    ]
