# Generated by Django 5.2.9 on 2026-01-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hearing',
            name='hearing_status',
            field=models.CharField(choices=[('filed', 'Filed'), ('pending_schedule', 'Pending Schedule'), ('scheduled', 'Scheduled'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('pending_decision', 'Pending Decision')], default='pending_schedule', max_length=20),
        ),
    ]
