# Generated by Django 5.2.7 on 2025-10-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hearing',
            name='hearing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hearing',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
