# Generated by Django 5.2.9 on 2026-01-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonWorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('reason', models.CharField(choices=[('holiday', 'Holiday'), ('typhoon', 'Typhoon/Weather'), ('event', 'Barangay Event'), ('other', 'Other')], default='holiday', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Non-Working Day',
                'verbose_name_plural': 'Non-Working Days',
                'ordering': ['-date'],
            },
        ),
    ]
