# Generated by Django 5.2.9 on 2026-02-05 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_persons', '0001_initial'),
        ('hearings', '0002_alter_hearing_hearing_status'),
        ('lupon_members', '0003_luponmember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='hearing',
            name='time_completed',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HearingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_role', models.CharField(choices=[('lupon', 'Lupon Member'), ('complainant', 'Complainant'), ('respondent', 'Respondent')], max_length=20)),
                ('attendance_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('excused', 'Excused')], default='present', max_length=10)),
                ('remarks', models.TextField(blank=True, help_text='Reason for absence or other notes', null=True)),
                ('case_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_person_attendances', to='case_persons.caseperson')),
                ('hearing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='hearings.hearing')),
                ('lupon_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lupon_attendances', to='lupon_members.luponmember')),
            ],
            options={
                'verbose_name_plural': 'Hearing Attendances',
            },
        ),
    ]
