# Generated by Django 5.2.7 on 2025-11-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearings', '0002_alter_hearing_hearing_date_alter_hearing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='hearing',
            name='hearing_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hearing',
            name='hearing_status',
            field=models.CharField(choices=[('filed', 'Filed'), ('pending_schedule', 'Pending Schedule'), ('scheduled', 'Scheduled'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('pending_decision', 'Pending Decision')], default='pending_schedule', max_length=20),
        ),
    ]
