# Generated by Django 5.2.9 on 2026-02-05 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hearings', '0002_nonworkingday'),
        ('hearings', '0003_hearing_time_completed_hearingattendance'),
    ]

    operations = [
    ]
