# Generated by Django 5.2.9 on 2026-01-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearings', '0003_hearing_hearing_number_alter_hearing_hearing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hearing',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
