# Generated by Django 5.2.9 on 2026-02-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearings', '0004_merge_20260206_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hearing',
            name='time_completed',
        ),
        migrations.AlterField(
            model_name='hearing',
            name='hearing_status',
            field=models.CharField(choices=[('filed', 'Filed'), ('pending_schedule', 'Pending Schedule'), ('scheduled', 'Scheduled'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('pending_decision', 'Pending Decision')], default='pending_schedule', max_length=20),
        ),
    ]
