# Generated by Django 5.2.9 on 2026-02-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearings', '0005_remove_hearing_time_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hearing',
            name='hearing_completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
