# Generated by Django 5.2.9 on 2026-02-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearings', '0006_hearing_hearing_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hearing',
            name='is_overtime',
            field=models.BooleanField(default=False, help_text='Whether this hearing is scheduled during overtime hours (after 4 PM)'),
        ),
    ]
