# Generated by Django 5.2.9 on 2026-01-17 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetrainConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_retrain_enabled', models.BooleanField(default=True)),
                ('threshold_cases', models.IntegerField(default=10, help_text='Number of new resolved cases before auto-retrain')),
                ('cases_since_last_train', models.IntegerField(default=0)),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
                ('default_epochs', models.IntegerField(default=50)),
                ('default_validation_split', models.FloatField(default=0.2)),
            ],
            options={
                'verbose_name': 'Retrain Configuration',
                'verbose_name_plural': 'Retrain Configuration',
            },
        ),
        migrations.CreateModel(
            name='TrainingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.CharField(choices=[('manual', 'Manual Trigger'), ('automatic', 'Automatic Threshold'), ('initial', 'Initial Training')], default='manual', max_length=50)),
                ('samples_trained', models.IntegerField(default=0)),
                ('final_loss', models.FloatField(blank=True, null=True)),
                ('val_loss', models.FloatField(blank=True, null=True)),
                ('epochs_trained', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('backup_location', models.CharField(blank=True, max_length=255)),
                ('triggered_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_trainings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Training Histories',
                'ordering': ['-trained_at'],
            },
        ),
    ]
