# Generated by Django 5.2.9 on 2026-01-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininghistory',
            name='mape_days',
            field=models.FloatField(blank=True, help_text='MAPE for days prediction (%)', null=True),
        ),
        migrations.AddField(
            model_name='traininghistory',
            name='mape_hearings',
            field=models.FloatField(blank=True, help_text='MAPE for hearings prediction (%)', null=True),
        ),
    ]
