# Generated by Django 5.2.9 on 2026-01-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_calendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSyncSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_sync_enabled', models.BooleanField(default=False, help_text='Enable automatic syncing of hearings to Google Calendar')),
                ('sync_on_create', models.BooleanField(default=True, help_text='Sync when a new hearing is created')),
                ('sync_on_update', models.BooleanField(default=True, help_text='Sync when a hearing is updated')),
                ('sync_on_delete', models.BooleanField(default=True, help_text='Remove from calendar when a hearing is deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Calendar Sync Settings',
                'verbose_name_plural': 'Calendar Sync Settings',
            },
        ),
    ]
