# Generated by Django 5.2.9 on 2026-02-17 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_calendar', '0002_add_calendar_sync_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCalendarSyncPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_filter', models.CharField(choices=[('all', 'All Hearings'), ('my_hearings', 'Only My Hearings'), ('selected', 'Selected Hearings Only')], default='my_hearings', help_text="Which hearings to sync to this user's Google Calendar", max_length=20)),
                ('selected_hearing_ids', models.JSONField(blank=True, default=list, help_text="List of hearing IDs to sync (only used when sync_filter='selected')")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_sync_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
