# Generated by Django 5.2.7 on 2025-10-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lupon_members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luponmember',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
