# Generated by Django 5.2.7 on 2025-10-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lupon_members', '0002_alter_luponmember_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='luponmember',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('staff', 'Staff')], default='admin', max_length=20),
        ),
    ]
