# Generated by Django 5.2.7 on 2025-10-30 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template_type', models.CharField(choices=[('summon', 'Summon Letter'), ('no-show', 'No-Show Letter'), ('monitoring', 'Case Monitoring Sheet'), ('appointment', 'Appointment Form'), ('cancellation', 'Cancellation Notice')], max_length=50)),
                ('html_content', models.TextField()),
                ('css_styles', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=100)),
                ('generated_data', models.JSONField()),
                ('generated_html', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documenttemplate')),
            ],
        ),
    ]
