# Generated by Django 5.2.7 on 2025-11-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='template_type',
            field=models.CharField(choices=[('summon', 'Summon Letter'), ('no-show', 'No-Show Letter'), ('monitoring', 'Case Monitoring Sheet'), ('appointment', 'Appointment Form'), ('cancellation', 'Cancellation Notice'), ('court', 'Court Certification')], max_length=50),
        ),
    ]
