# Generated by Django 5.2.9 on 2026-03-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documenttemplate_template_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttemplate',
            name='css_styles',
        ),
        migrations.RemoveField(
            model_name='documenttemplate',
            name='html_content',
        ),
        migrations.RemoveField(
            model_name='generateddocument',
            name='generated_html',
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='docx_file',
            field=models.FileField(blank=True, null=True, upload_to='templates/docs/'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='generated_file',
            field=models.FileField(blank=True, null=True, upload_to='generated_docs/'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='template_type',
            field=models.CharField(max_length=50),
        ),
    ]
