# Generated by Django 5.2.9 on 2026-01-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('barangay', models.CharField(default='Tetuan', max_length=100)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
