# Generated by Django 5.2.9 on 2026-01-13 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case_persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=100)),
                ('severity', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SettlementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending_approval', max_length=20)),
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_filed', models.DateTimeField(auto_now_add=True)),
                ('predicted_hearings', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('rejection_section', models.CharField(blank=True, choices=[('none', 'None'), ('case_details', 'Case Details'), ('complainant_info', 'Complainant Information'), ('respondent_info', 'Respondent Information')], default='none', max_length=30, null=True)),
                ('complainants', models.ManyToManyField(related_name='cases_as_complainant', to='case_persons.caseperson')),
                ('respondents', models.ManyToManyField(related_name='cases_as_respondent', to='case_persons.caseperson')),
                ('case_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='cases.casetype')),
                ('relationship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='cases.relationship')),
                ('settlement_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='cases.settlementtype')),
            ],
        ),
    ]
