# Generated by Django 5.2.9 on 2026-01-13 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='complainants',
        ),
        migrations.RemoveField(
            model_name='case',
            name='respondents',
        ),
    ]
