# Generated by Django 5.2.7 on 2025-10-10 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='description',
        ),
        migrations.AddField(
            model_name='case',
            name='case_status',
            field=models.CharField(choices=[('filed', 'Filed'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='filed', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='complainant_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='respondent_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respondent_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='severity',
            field=models.IntegerField(default=1),
        ),
    ]
