# Generated by Django 5.2.7 on 2025-10-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_remove_case_description_case_case_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
