# Generated by Django 5.2.9 on 2026-01-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_persons', '0001_initial'),
        ('cases', '0002_remove_case_complainants_remove_case_respondents'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='complainants',
            field=models.ManyToManyField(related_name='cases_as_complainant', to='case_persons.caseperson'),
        ),
        migrations.AddField(
            model_name='case',
            name='respondents',
            field=models.ManyToManyField(related_name='cases_as_respondent', to='case_persons.caseperson'),
        ),
    ]
