# Generated by Django 5.2.9 on 2026-01-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_complainants_case_respondents'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetype',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
