# Generated by Django 5.2.9 on 2026-01-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_complainants_case_respondents'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='summon_date_received',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='summon_received_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='summon_status',
            field=models.CharField(choices=[('served', 'Served'), ('not_served', 'Not Served'), ('pending', 'Pending'), ('refused', 'Refused')], default='pending', max_length=20),
        ),
    ]
