# Generated by Django 5.2.9 on 2026-01-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_summon_date_received_case_summon_received_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='summon_status',
            field=models.CharField(choices=[('served', 'Served'), ('not_served', 'Not Served'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
