# Generated by Django 5.2.7 on 2025-10-14 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_description'),
        ('respondents', '0002_alter_respondent_birth_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='complainant_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='respondent_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='respondents.respondent'),
        ),
    ]
