# Generated by Django 5.2.9 on 2026-01-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_add_is_custom_to_casetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='summon_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('sent', 'Sent'), ('received', 'Received'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
