# Generated by Django 5.2.7 on 2025-10-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_alter_case_complainant_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='co_complainants_ids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
