# Generated by Django 5.2.9 on 2026-01-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_alter_case_summon_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending_approval', max_length=20),
        ),
    ]
