# Generated by Django 5.2.9 on 2026-01-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_persons', '0001_initial'),
        ('cases', '0006_alter_case_case_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='complainants',
            field=models.ManyToManyField(blank=True, related_name='cases_as_complainant', to='case_persons.caseperson'),
        ),
        migrations.AlterField(
            model_name='case',
            name='respondents',
            field=models.ManyToManyField(blank=True, related_name='cases_as_respondent', to='case_persons.caseperson'),
        ),
    ]
