# Generated by Django 5.2.7 on 2025-11-11 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_case_predicted_hearings_case_remarks_and_more'),
        ('complainants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='complainant_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complainants.complainant'),
        ),
    ]
