# Generated by Django 5.2.9 on 2026-01-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_organizations', '0001_initial'),
        ('cases', '0007_alter_case_complainants_alter_case_respondents'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='complainant_organizations',
            field=models.ManyToManyField(blank=True, related_name='cases_as_complainant_org', to='case_organizations.caseorganization'),
        ),
        migrations.AddField(
            model_name='case',
            name='respondent_organizations',
            field=models.ManyToManyField(blank=True, related_name='cases_as_respondent_org', to='case_organizations.caseorganization'),
        ),
    ]
