# Generated by Django 5.2.9 on 2026-01-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_case_complainant_organizations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='pending_approval', max_length=20),
        ),
    ]
