# Generated by Django 5.2.7 on 2025-11-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_alter_case_complainant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='rejection_section',
            field=models.CharField(blank=True, choices=[('case_details', 'Case Details'), ('complainant_info', 'Complainant Information'), ('respondent_info', 'Respondent Information')], max_length=30, null=True),
        ),
    ]
