# Generated by Django 5.2.9 on 2026-02-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_alter_case_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='cfa_destination',
            field=models.CharField(blank=True, choices=[('municipal', 'Municipal'), ('pnp', 'PNP'), ('vawc', 'VAWC')], max_length=20, null=True),
        ),
    ]
