# Generated by Django 5.2.7 on 2025-11-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_case_rejection_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='rejection_section',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('case_details', 'Case Details'), ('complainant_info', 'Complainant Information'), ('respondent_info', 'Respondent Information')], default='none', max_length=30, null=True),
        ),
    ]
