# Generated by Django 5.2.7 on 2025-11-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_alter_case_rejection_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='co_respondents_ids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
