# Generated by Django 5.2.9 on 2026-02-05 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_case_cfa_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='complainant_organizations',
        ),
        migrations.RemoveField(
            model_name='case',
            name='respondent_organizations',
        ),
    ]
