# Generated by Django 5.2.7 on 2025-12-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_case_co_respondents_ids'),
        ('complainants', '0004_complainant_with_account'),
        ('respondents', '0003_alter_respondent_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='co_complainants_ids',
        ),
        migrations.RemoveField(
            model_name='case',
            name='co_respondents_ids',
        ),
        migrations.RemoveField(
            model_name='case',
            name='complainant_user',
        ),
        migrations.RemoveField(
            model_name='case',
            name='respondent_user',
        ),
        migrations.AddField(
            model_name='case',
            name='complainants',
            field=models.ManyToManyField(related_name='cases_as_complainant', to='complainants.complainant'),
        ),
        migrations.AddField(
            model_name='case',
            name='respondents',
            field=models.ManyToManyField(related_name='cases_as_respondent', to='respondents.respondent'),
        ),
    ]
