# Generated by Django 5.2.9 on 2026-02-05 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_summon_status'),
        ('cases', '0011_remove_case_complainant_organizations_and_more'),
    ]

    operations = [
    ]
