# Generated by Django 5.2.9 on 2026-02-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_persons', '0001_initial'),
        ('cases', '0012_merge_20260206_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending_approval', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='cfa_destination',
            field=models.CharField(blank=True, choices=[('municipal', 'Municipal'), ('pnp', 'PNP'), ('vawc', 'VAWC')], default='none', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='complainants',
            field=models.ManyToManyField(related_name='cases_as_complainant', to='case_persons.caseperson'),
        ),
        migrations.AlterField(
            model_name='case',
            name='respondents',
            field=models.ManyToManyField(related_name='cases_as_respondent', to='case_persons.caseperson'),
        ),
        migrations.AlterField(
            model_name='case',
            name='summon_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('served', 'Served'), ('not_served', 'Not Served'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
