# Generated by Django 5.2.9 on 2026-02-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_alter_case_case_status_alter_case_cfa_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='actual_hearings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='case_completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_status',
            field=models.CharField(choices=[('filed', 'Filed'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending_approval', max_length=20),
        ),
    ]
