# Generated by Django 5.2.9 on 2026-02-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_case_actual_hearings_case_case_completed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='create_by',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('admin', 'Admin')], default='none', max_length=20, null=True),
        ),
    ]
