# Generated by Django 5.2.9 on 2026-02-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_case_create_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='approved_case_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='rejected_case_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
