# Generated by Django 5.2.9 on 2026-03-03 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_case_approved_case_date_case_rejected_case_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfa', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='case',
            name='cfa_destination',
        ),
        migrations.AddField(
            model_name='case',
            name='cfa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='cases.cfa'),
        ),
    ]
