# Generated by Django 5.2.9 on 2026-02-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_case_approved_case_date_case_rejected_case_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='cfa_destination',
            field=models.CharField(blank=True, choices=[('court', 'Municipal'), ('pnp', 'PNP'), ('vawc', 'VAWC')], default='none', max_length=20, null=True),
        ),
    ]
