# Generated by Django 5.2.7 on 2025-10-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_birth_date_user_contact_number_user_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='barangay',
            field=models.CharField(default='Tetuan', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
