# Generated by Django 5.2.9 on 2025-12-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_auth_provider_user_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_account_verified',
            field=models.BooleanField(default=False),
        ),
    ]
