# Generated by Django 5.2.9 on 2026-01-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_notificationpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_identity_verified',
            field=models.BooleanField(default=False),
        ),
    ]
